AWSTemplateFormatVersion: 2010-09-09
Description: >-
  security_compliance_checker

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100


Resources:

# Lambda Functions
  getEvidencesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-evidences.getEvidencesHandler
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EvidenceTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          EVIDENCE_TABLE: !Ref EvidenceTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  postEvidenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/post-evidences.putItemHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EvidenceTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          EVIDENCE_TABLE: !Ref EvidenceTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /evidences

  getFindingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-findings.getFindingsHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref FindingTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          FINDING_TABLE: !Ref FindingTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /findings
            Method: GET

  postFindingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/post-findings.putItemHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref FindingTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          FINDING_TABLE: !Ref FindingTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /findings
            Method: POST

    # DynamoDB Table for Findings

# DynamoDB Tables
  FindingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Findings"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: findingId
          AttributeType: S
        - AttributeName: assignedTo
          AttributeType: S
      KeySchema:
        - AttributeName: findingId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: assignedToIndex
          KeySchema:
            - AttributeName: assignedTo
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: SecurityComplianceChecker
  
  EvidenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Evidence"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: evidenceId
          AttributeType: S
        - AttributeName: findingId
          AttributeType: S
      KeySchema:
        - AttributeName: evidenceId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: findingIdIndex
          KeySchema:
            - AttributeName: findingId
              KeyType: HASH
          Projection:
            ProjectionType: ALL



Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  
  FindingsTableNam:
    Description: "DynamoDB Findings Table Name"
    Value: !Ref FindingsTable
  
  EvidenceTableName:
    Description: "DynamoDB Evidence Table Name"
    Value: !Ref EvidenceTable