AWSTemplateFormatVersion: 2010-09-09
Description: >-
  security_compliance_checker

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100

Parameters:
  PrerequisiteStackName:
    Type: String
    Default: security-compliance-checker-prerequisite
    Description: Name of the prerequisite stack that contains Cognito, DynamoDB, S3, and SNS

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: SecurityComplianceAPI
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - UserPoolArn

  GetEvidencesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-evidences.getEvidencesHandler
      Description: Get evidences - returns all for admin, filtered by assigned findings for regular users
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - CaseTableName
        - S3ReadWritePolicy:
            BucketName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - EvidenceBucketName
        - SNSPublishMessagePolicy:
            TopicName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - NotificationTopicArn
      Environment:
        Variables:
          TABLE_NAME: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - CaseTableName
          EVIDENCE_BUCKET: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - EvidenceBucketName
          SNS_TOPIC_ARN: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - NotificationTopicArn
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /evidence
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  PostEvidenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/post-evidences.postEvidencesHandler
      Description: Create evidence - admins can create for any finding, users only for assigned findings
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - CaseTableName
        - S3ReadWritePolicy:
            BucketName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - EvidenceBucketName
        - SNSPublishMessagePolicy:
            TopicName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - NotificationTopicArn
      Environment:
        Variables:
          TABLE_NAME: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - CaseTableName
          EVIDENCE_BUCKET: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - EvidenceBucketName
          SNS_TOPIC_ARN: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - NotificationTopicArn
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /evidence
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  GetFindingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-findings.getFindingsHandler
      Description: Get findings - returns all for admin, only assigned findings for regular users
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - CaseTableName
        - S3ReadWritePolicy:
            BucketName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - EvidenceBucketName
        - SNSPublishMessagePolicy:
            TopicName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - NotificationTopicArn
      Environment:
        Variables:
          TABLE_NAME: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - CaseTableName
          EVIDENCE_BUCKET: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - EvidenceBucketName
          SNS_TOPIC_ARN: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - NotificationTopicArn
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /finding
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  PostFindingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/post-findings.postFindingsHandler
      Description: Create finding - admin only
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - CaseTableName
        - S3ReadWritePolicy:
            BucketName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - EvidenceBucketName
        - SNSPublishMessagePolicy:
            TopicName: !ImportValue 
              Fn::Join:
                - '-'
                - - !Ref PrerequisiteStackName
                  - NotificationTopicArn
      Environment:
        Variables:
          TABLE_NAME: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - CaseTableName
          EVIDENCE_BUCKET: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - EvidenceBucketName
          SNS_TOPIC_ARN: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - NotificationTopicArn
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /finding
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
  
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/login.loginHandler
      Description: Login function to authenticate users with Cognito
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminInitiateAuth
              Resource: !ImportValue 
                Fn::Join:
                  - '-'
                  - - !Ref PrerequisiteStackName
                    - UserPoolArn
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - UserPoolId
          CLIENT_ID: !ImportValue 
            Fn::Join:
              - '-'
              - - !Ref PrerequisiteStackName
                - UserPoolClientId
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /login
            Method: POST
            Auth:
              Authorizer: NONE

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  PrerequisiteStackReference:
    Description: "Reference to prerequisite stack resources"
    Value: !Ref PrerequisiteStackName
